package vista;

import controlador.ControladorLogin;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Usuario;
import utilidades.Sesion;

/**
 *
 * @author Lud
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // Ícono de la aplicación (esquina de la ventana y barra de tareas)
        utilidades.Iconos.aplicarA(this);
        setLocationRelativeTo(null);
        txpPassword.setForeground(new java.awt.Color(0, 0, 0));
        txpPassword.setText("");
        btnIngresar.setOpaque(true);
        btnIngresar.setBackground(new java.awt.Color(0, 102, 102));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBackground = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        sptrPassword = new javax.swing.JSeparator();
        lblUsuario = new javax.swing.JLabel();
        txpPassword = new javax.swing.JPasswordField();
        sptrUsuario = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        lblHorarionet = new javax.swing.JLabel();
        lblLogoHorarionet = new javax.swing.JLabel();
        LblUTM = new javax.swing.JLabel();
        lblIconoUser = new javax.swing.JLabel();
        lblIconoPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIENVENIDO");

        PnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        PnlBackground.setForeground(new java.awt.Color(255, 255, 255));
        PnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login_banner_escuela600x200.png"))); // NOI18N
        PnlBackground.add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        LblPassword.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(0, 0, 0));
        LblPassword.setText("CONTRASEÑA");
        PnlBackground.add(LblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Ingrese su usuario aqui.");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        PnlBackground.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 210, -1));
        PnlBackground.add(sptrPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 210, 20));

        lblUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("USUARIO O MATRICULA");
        PnlBackground.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        txpPassword.setForeground(new java.awt.Color(0, 0, 0));
        txpPassword.setBackground(new java.awt.Color(255, 255, 255));
        txpPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txpPassword.setText("jPasswordField1");
        txpPassword.setBorder(null);
        txpPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txpPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txpPasswordFocusLost(evt);
            }
        });
        PnlBackground.add(txpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 210, -1));
        PnlBackground.add(sptrUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 210, 20));

        btnIngresar.setBackground(new java.awt.Color(0, 102, 102));
        btnIngresar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        PnlBackground.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 200, -1));

        lblBienvenido.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(102, 102, 102));
        lblBienvenido.setText("¡Bienvenido!");
        PnlBackground.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 229, 60));

        lblHorarionet.setFont(new java.awt.Font("Teko Medium", 3, 50)); // NOI18N
        lblHorarionet.setForeground(new java.awt.Color(102, 102, 102));
        lblHorarionet.setText("HorarioNet");
        PnlBackground.add(lblHorarionet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 198, -1));

        lblLogoHorarionet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoHorarionet_Gris67x60.png"))); // NOI18N
        PnlBackground.add(lblLogoHorarionet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        LblUTM.setForeground(new java.awt.Color(0, 0, 0));
        LblUTM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_grisUTM142x50.png"))); // NOI18N
        PnlBackground.add(LblUTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 70));

        lblIconoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_login_usuario.png"))); // NOI18N
        PnlBackground.add(lblIconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        lblIconoPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_login_password.png"))); // NOI18N
        PnlBackground.add(lblIconoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = txtUsuario.getText().trim();
        String contrasena = new String(txpPassword.getPassword()).trim();

        ControladorLogin controlador = new ControladorLogin();
        boolean exito = controlador.iniciarSesion(usuario, contrasena);

        if (!exito) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de acceso", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Usuario u = Sesion.getUsuario();

        // Cada rol abre su propia ventana principal
        switch (u.getTipoUsuario()) {
            case "administrador":
                new vista.FrmMenuAdministrador().setVisible(true);
                this.dispose();
                break;
            case "docente":
                new vista.FrmMenuDocente().setVisible(true);
                this.dispose();
                break;
            case "alumno":
                new vista.FrmHorarioAlumno().setVisible(true);
                this.dispose();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Rol no reconocido.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("Ingrese su usuario aqui.")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.BLACK);
}    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Ingrese su usuario aqui.");
            txtUsuario.setForeground(Color.GRAY);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txpPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpPasswordFocusGained
        txpPassword.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txpPasswordFocusGained

    private void txpPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpPasswordFocusLost
        //txpPassword.setText("*********"); 
    }//GEN-LAST:event_txpPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        System.setProperty("flatlaf.menuBarEmbedded", "false");

try {
    com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialOceanicIJTheme.setup();
} catch (Exception ex) {
    ex.printStackTrace();
}

UIManager.put("TableHeader.background", new Color(0xF2D9A0));
UIManager.put("TableHeader.foreground", Color.BLACK);

/*
 * Estilo de los combobox, en un solo lugar.
 *
 * Antes heredaban el vino institucional de fondo con la letra clara del tema
 * oscuro de FlatLaf, y sobre el panel color crema costaba trabajo leerlos.
 * Ahora van en #F0F8FF con letra negra sólida: máximo contraste y combinan
 * con las cajas de texto, que también son claras.
 *
 * Esto cubre los combos que no traen color propio. Los que sí lo traen (los
 * de alumnos, horarios, permisos-rol y consulta) se pusieron en ese mismo
 * color uno por uno, para que la vista Diseño de NetBeans los muestre igual
 * que la aplicación corriendo.
 */
Color fondoCombo = new Color(0xF0F8FF);

UIManager.put("ComboBox.background", fondoCombo);
UIManager.put("ComboBox.foreground", Color.BLACK);
UIManager.put("ComboBox.buttonBackground", fondoCombo);
UIManager.put("ComboBox.buttonEditableBackground", fondoCombo);
UIManager.put("ComboBox.buttonArrowColor", new Color(0x7A1F2B));
UIManager.put("ComboBox.buttonHoverArrowColor", new Color(0x7A1F2B));

// La lista que se despliega al dar clic
UIManager.put("ComboBox.selectionBackground", new Color(0x7A1F2B));
UIManager.put("ComboBox.selectionForeground", Color.WHITE);

        javax.swing.UIManager.getLookAndFeelDefaults().put("TitlePane.unifiedBackground", false);
        javax.swing.UIManager.getLookAndFeelDefaults().put("TitlePane.background", new java.awt.Color(65, 105, 225));
        javax.swing.UIManager.getLookAndFeelDefaults().put("TitlePane.foreground", java.awt.Color.WHITE);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblUTM;
    private javax.swing.JPanel PnlBackground;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblHorarionet;
    private javax.swing.JLabel lblIconoPass;
    private javax.swing.JLabel lblIconoUser;
    private javax.swing.JLabel lblLogoHorarionet;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JSeparator sptrPassword;
    private javax.swing.JSeparator sptrUsuario;
    private javax.swing.JPasswordField txpPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
/*
Donna toki mo... kanjite hoshii no
Kono omoi wo
Orenai tsubasa de watashi no uta
Motto motto todokeru kara <3

*/